version: '3.8'
services:
  # Сервис базы данных
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRESDB_DATABASE}
    ports:
      - ${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}
    volumes:
      - db_data:/var/lib/postgresql

  # Сервис самого приложения
  app:
    build: .
    restart: always
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    environment:
      - DB_HOST=db
      - DB_USER=${POSTGRESDB_USER}
      - DB_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - DB_NAME=${POSTGRESDB_DATABASE}
      - DB_PORT=${POSTGRESDB_DOCKER_PORT}
    depends_on:
      - db

volumes:
  db_data: